---
services:
  db:
    image: postgres
    volumes:
      - "./tmp/db:/var/lib/postgresql/data"

  redis:
    image: redis

  sidekiq:
    depends_on:
      - db
      - redis
    build:
      context: .
      dockerfile: "./docker/app/Dockerfile"
    command: "bundle exec sidekiq"
    volumes:
      - "bundle_cache:/bundle"
      - ".:/app"
    env_file:
      - ".env"
  web:
    build:
      context: .
      dockerfile: "./docker/web/Dockerfile"
    depends_on:
      - app
    ports:
      - 8080:80

  app:
    build:
      context: .
      dockerfile: "./docker/app/Dockerfile"
    command: "bundle exec rails s -p 3000 -b '0.0.0.0'"
    depends_on:
      - db
      - redis
    expose:
      - "3000"
    volumes:
      - "bundle_cache:/bundle"
      - ".:/app"
    env_file:
      - ".env"
version: "3.1"
volumes:
  bundle_cache: ~
